project:
  type: website
  output-dir: docs
  resources:
    - presentation.pdf

website:
  navbar:
    left:
      - href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Proposal"
        href: proposal.qmd
      - text: "Presentation"
        href: presentation.pdf
      - text: "Report"
        href: report.qmd

format:
  html:
    theme: default
    toc: true