<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.1.251">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Billionaire Wealth</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html">Team 2 - Billionaire Wealth</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html">About</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./proposal.html">Proposal</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./presentation.pdf">Presentation</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./report.html" aria-current="page">Report</a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction-and-data" id="toc-introduction-and-data" class="nav-link active" data-scroll-target="#introduction-and-data">Introduction and Data</a></li>
  <li><a href="#literature-review" id="toc-literature-review" class="nav-link" data-scroll-target="#literature-review">Literature Review</a></li>
  <li><a href="#methodology" id="toc-methodology" class="nav-link" data-scroll-target="#methodology">Methodology</a>
  <ul class="collapse">
  <li><a href="#housekeeping" id="toc-housekeeping" class="nav-link" data-scroll-target="#housekeeping">Housekeeping</a></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a>
  <ul class="collapse">
  <li><a href="#single-variable-linear-regression-models" id="toc-single-variable-linear-regression-models" class="nav-link" data-scroll-target="#single-variable-linear-regression-models">Single variable linear regression models</a></li>
  <li><a href="#two-variable-linear-regression-models" id="toc-two-variable-linear-regression-models" class="nav-link" data-scroll-target="#two-variable-linear-regression-models">Two variable linear regression models</a></li>
  <li><a href="#three-variable-linear-regression-models" id="toc-three-variable-linear-regression-models" class="nav-link" data-scroll-target="#three-variable-linear-regression-models">Three variable linear regression models</a></li>
  </ul></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  <li><a href="#works-cited" id="toc-works-cited" class="nav-link" data-scroll-target="#works-cited">Works Cited</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Billionaire Wealth</h1>
<p class="subtitle lead">Report</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Emily Wang, Valentina Garbelotto, Teresa Chen, Karen Dong, &amp; Sneha Sengupta </p>
          </div>
  </div>
    
    
  </div>
  

</header>

<section id="introduction-and-data" class="level1">
<h1>Introduction and Data</h1>
<p>To the average person, the modern billionaire is at once mysterious and completely scrutable. Few will ever come face to face with a billionaire, yet many can name the likes of Jeff Bezos and Bill Gates and a fact or two about each. While these billionaires sit on enormous wealth, 47% of the world lives on less than $6.85 per day, and 84% lives on less than $30 per day [1]. Moreover, the past two decades have seen a steep increase in global inequality as the world’s billionaires have captured an increasing proportion of global wealth [2]. Our realities of poverty among wealth and stark inequality thus incite questions about how world leaders should engage with billionaire wealth - was this wealth justly acquired? What are the ethics of wealth re-distribution? Wealth accumulation also invites larger philosophical questions of how society values or devalues certain activities over others.</p>
<p>Given these considerations, in this report, we investigate the potential sources of billionaire wealth. Specifically, we assess the question of how do wealth category, citizenship, and wealth type relate to billionaire net worths in 2014?</p>
<p>We hypothesize that financial wealth, European citizenship, and inheritance are related to billionaires having higher net worths. To begin with, our team hypothesizes that financial wealth relates to billionaires with higher net worths given that banking and finance have served the largest primary industries for up to 20.4% of the total billionaire population, according to the Billionaire Census 2022 [4]. Primary industries suggest where the billionaires devoted most of their time and by which they created most of their wealth. Second, we hypothesize that inheritance also associates with higher net worths of billionaires due to the link between increased inheritance flows and increased wealth distribution identified by several studies [5]. Finally, we associate European citizenship with higher net worths of billionaires as the third component of the hypothesis, as Europe’s billionaire wealth has been growing the fastest, up 22% year-over-year in 2021 [6].</p>
<p>Our data comes from the “billionaires” data set, which we obtained from the CORGIS Dataset Project. This data set was created by Ryan Whitcomb in 2016 and originally sourced from a report by Caroline Freund and Sarah Oliver of the Peterson Institute for International Economics. Freund and Oliver derived their data set from Forbes World’s Billionaires lists from 1996-2014 [3]. Forbes journalists drew from shareholder information, company financial statements, current exchange rates, and meetings with candidates to estimate billionaire net worths. From 1996-2010, the Forbes data included name, rank, citizenship, and net worth. Then, in 2011, Forbes added the source of wealth (company or sector).</p>
<p>Freund and Oliver supplemented the Forbes data with additional variables that describe the characteristics of billionaires and their businesses. The “billionaires” data set includes information on billionaires taken at three-time points: 1996, 2001, and 2014.</p>
<p>This report focuses on four variables: wealth, wealth type, wealth category, and citizenship. Following is a brief description of each variable of interest:</p>
<ol type="1">
<li><p>Wealth - Called “wealth.worth.in.billions” in the data set. A continuous numeric variable that describes the wealth in billions for each observation, where one observation is one billionaire at one time point.</p></li>
<li><p>Wealth type - Called “wealth.type” in the data set. A nominal categorical variable that describes the type of wealth. For billionaires in 2014, there are four wealth types: founder, inherited, privatized, and self-made.</p></li>
<li><p>Wealth category - Called “wealth.how.category” in the data set. A nominal categorical variable that describes the category of wealth. For billionaires in 2014, there are six wealth categories: energy, financial, new, non-traded, resource, and traded.</p></li>
<li><p>Citizenship - Called “location.citizenship” in the data set. A nominal categorical variable that describes the country of citizenship of the billionaire. In this report, we group citizenship into Europe and Not Europe.</p></li>
</ol>
<p>The method by which information for this data set was collected priimarily raises two ethical concerns. First, when data collection involves human subjects, it is best practice to obtain the subjects’ consent. Although the Forbes journalists conducted interviews with subjects, it is unclear whether the journalists obtained the consent of all the billionaires that they collected data on. Moreover, it is unclear whether how Forbes obtained shareholder information and company financial statements. Second, this data set contains extensive personal identifying information about individuals, which may conflict for practices of de-identifying subjects and preserving subjects’ anonymity.</p>
</section>
<section id="literature-review" class="level1">
<h1>Literature Review</h1>
<p>Freund, Caroline, and Sarah Oliver. “The origins of the superrich: the billionaire characteristics database.”Peterson Institute for International Economics Working Paper 16-1 (2016).</p>
<p><strong>Summary:</strong></p>
<p>This article directly addresses the origins of how billionaires get their wealth and what characteristics contributed to the rise of their wealth. The article specifies the age of billionaires as they reach the milestones of becoming millionaires and onwards. It looks into what economic sectors they work in and how much those sectors contributed to their wealth and compares the trends between Europe and America. They also compare personal factors like age and family inheritance.</p>
<p><strong>How our research differs:</strong></p>
<p>The research article analyzes and brings in new information on the impact of inheritance on accumulated wealth and net worth. We will specifically interrogate how significant of a role inheritance plays in wealth-building, which in an area that this article does not explicitly address.</p>
<p><strong>Additional published credible article:</strong></p>
<p>Sanandaji, Tino. “The international mobility of billionaires.” Small Business Economics 42 (2014): 329-338.</p>
<p><strong>Summary:</strong></p>
<p>This article uses Forbes Magazine’s list of billionaires and additional information to study the migration of billionaires and their sources of income that lead to them building their wealth and how their wealth interacts with the economy of the countries they live in and move to or from.</p>
<p>This study gives us better context on billionaires and the interactions of their wealth and movements that focuses on a couple of factors outside of the previous article and our own data set which could explain some of our own variables.</p>
</section>
<section id="methodology" class="level1">
<h1>Methodology</h1>
<section id="housekeeping" class="level2">
<h2 class="anchored" data-anchor-id="housekeeping">Housekeeping</h2>
<p>First, we load and glimpse our data:</p>
<div class="cell">

</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 2,614
Columns: 22
$ name                       &lt;chr&gt; "Bill Gates", "Bill Gates", "Bill Gates", "…
$ rank                       &lt;dbl&gt; 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5…
$ year                       &lt;dbl&gt; 1996, 2001, 2014, 1996, 2001, 2014, 1996, 2…
$ company.founded            &lt;dbl&gt; 1975, 1975, 1975, 1962, 1962, 1990, 1896, 1…
$ company.name               &lt;chr&gt; "Microsoft", "Microsoft", "Microsoft", "Ber…
$ company.relationship       &lt;chr&gt; "founder", "founder", "founder", "founder",…
$ company.sector             &lt;chr&gt; "Software", "Software", "Software", "Financ…
$ company.type               &lt;chr&gt; "new", "new", "new", "new", "new", "privati…
$ demographics.age           &lt;dbl&gt; 40, 45, 58, 65, 70, 74, 0, 48, 77, 68, 56, …
$ demographics.gender        &lt;chr&gt; "male", "male", "male", "male", "male", "ma…
$ location.citizenship       &lt;chr&gt; "United States", "United States", "United S…
$ `location.country code`    &lt;chr&gt; "USA", "USA", "USA", "USA", "USA", "MEX", "…
$ location.gdp               &lt;dbl&gt; 8.10e+12, 1.06e+13, 0.00e+00, 8.10e+12, 1.0…
$ location.region            &lt;chr&gt; "North America", "North America", "North Am…
$ wealth.type                &lt;chr&gt; "founder non-finance", "founder non-finance…
$ wealth.worth               &lt;dbl&gt; 18.5, 58.7, 76.0, 15.0, 32.3, 72.0, 13.1, 3…
$ wealth.how.category        &lt;chr&gt; "New Sectors", "New Sectors", "New Sectors"…
$ `wealth.how.from emerging` &lt;lgl&gt; TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, T…
$ wealth.how.industry        &lt;chr&gt; "Technology-Computer", "Technology-Computer…
$ wealth.how.inherited       &lt;chr&gt; "not inherited", "not inherited", "not inhe…
$ `wealth.how.was founder`   &lt;lgl&gt; TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, T…
$ `wealth.how.was political` &lt;lgl&gt; TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, T…</code></pre>
</div>
</div>
<p>Next, we wrangle the data. 1. We coerce the variables to have valid names for our analysis.</p>
<div class="cell">

</div>
<ol start="2" type="1">
<li>We filter the data to only include data from 2014.</li>
</ol>
<div class="cell">

</div>
<ol start="3" type="1">
<li>We create a new citizenship variable that describes whether or not the billionaire holds European citizenship.</li>
</ol>
<div class="cell">

</div>
<ol start="4" type="1">
<li>Next, we compute mean, median, and standard deviation of net worth for each potential outcome for our variables of interest.</li>
</ol>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 4
  m_wealth me_wealth sd_wealth na.rm
     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt; &lt;lgl&gt;
1     3.90       2.1      5.75 TRUE </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 18 × 5
   wealth.how.industry             m_industry me_industry sd_industry na.rm
   &lt;chr&gt;                                &lt;dbl&gt;       &lt;dbl&gt;       &lt;dbl&gt; &lt;lgl&gt;
 1 0                                     1.27        1.2        0.320 TRUE 
 2 Constrution                           2.88        1.8        3.44  TRUE 
 3 Consumer                              4.05        2.4        5.81  TRUE 
 4 Diversified financial                 4.65        2.5        6.39  TRUE 
 5 Energy                                3.91        2.1        4.24  TRUE 
 6 Hedge funds                           3.89        2          4.57  TRUE 
 7 Media                                 4.72        2.45       8.10  TRUE 
 8 Mining and metals                     3.54        1.7        4.00  TRUE 
 9 Money Management                      3.13        2.05       2.94  TRUE 
10 Non-consumer industrial               3.60        2          3.81  TRUE 
11 Other                                 3.04        2.1        2.77  TRUE 
12 Private equity/leveraged buyout       3.99        2.9        3.21  TRUE 
13 Real Estate                           3.02        2          3.70  TRUE 
14 Retail, Restaurant                    4.72        2.45       7.81  TRUE 
15 Technology-Computer                   5.23        2.2        9.20  TRUE 
16 Technology-Medical                    2.79        1.85       2.51  TRUE 
17 Venture Capital                       2.22        1.9        0.847 TRUE 
18 &lt;NA&gt;                                  1.1         1.1       NA     TRUE </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 5
  wealth.how.category m_category me_category sd_category na.rm
  &lt;chr&gt;                    &lt;dbl&gt;       &lt;dbl&gt;       &lt;dbl&gt; &lt;lgl&gt;
1 0                         2.69        1.95        2.26 TRUE 
2 energy                    1.9         1.9        NA    TRUE 
3 Financial                 3.56        2.2         4.49 TRUE 
4 New Sectors               4.31        2           7.53 TRUE 
5 Non-Traded Sectors        4.39        2.3         7.33 TRUE 
6 Resource Related          3.99        2.1         4.39 TRUE 
7 Traded Sectors            3.86        2.25        5.38 TRUE 
8 &lt;NA&gt;                      5           5          NA    TRUE </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  citizenship_euro m_citizen me_citizen sd_citizen na.rm
  &lt;chr&gt;                &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt; &lt;lgl&gt;
1 Europe                4.04        2.3       5.26 TRUE 
2 Not Europe            3.85        2.1       5.94 TRUE </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
  wealth.type              m_inherited me_inherited sd_inherited na.rm
  &lt;chr&gt;                          &lt;dbl&gt;        &lt;dbl&gt;        &lt;dbl&gt; &lt;lgl&gt;
1 executive                       2.70          1.8        3.52  TRUE 
2 founder non-finance             4.12          2.2        7.07  TRUE 
3 inherited                       4.41          2.6        5.50  TRUE 
4 privatized and resources        4.01          2          6.33  TRUE 
5 self-made finance               3.31          2          4.22  TRUE 
6 &lt;NA&gt;                            3.2           3.2        0.141 TRUE </code></pre>
</div>
</div>
<ol start="5" type="1">
<li>Using the above data, we create box plots that visualize how each variable affects the distribution of billionaire net worths.</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<p><img src="report_files/figure-html/box-plot-citizen-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="report_files/figure-html/box-plot-cat-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="report_files/figure-html/box-plot-inh-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ol start="6" type="1">
<li>We also created a box plot to visualize the difference in net worth between billionaires who did and did not inherit money.</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<p><img src="report_files/figure-html/scatter_inherit-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ol start="7" type="1">
<li>Additionally, for each of our variables of interest, we compute the proportion of billionaires associated with each outcome.</li>
</ol>
<div class="cell">

</div>
<ol start="8" type="1">
<li>Using the above data, we create pie chart visualizations.</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<p><img src="report_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="report_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="report_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="report_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>To evaluate our research question and to test our hypothesis, we selected a linear regression methodology since it is a common method to model relationships between dependent variables (billionaire net worth) and one or more independent variables (financial wealth, European citizenship, and inheritance). Moreover, it allows us to quantify the strength and direction of the relationship between the independent variables and the dependent variable. If the results of the linear regression analysis show a significant relationship between financial wealth, European citizenship, and inheritance and higher net worths of billionaires, then the data would support the hypothesis.</p>
</section>
</section>
<section id="results" class="level1">
<h1>Results</h1>
<section id="single-variable-linear-regression-models" class="level2">
<h2 class="anchored" data-anchor-id="single-variable-linear-regression-models">Single variable linear regression models</h2>
<div class="cell">

</div>
<p>AIC = 10474.78</p>
<div class="cell">

</div>
<p>AIC = 10458.57</p>
<div class="cell">

</div>
<p>AIC = 10477.63</p>
<p>The second model, lin-reg-wealth-type, is the best fit model when looking at a single variable linear regression. This model indicates the relationship between net worth and wealth type and we know it is the best fit model for our data because the AIC value is the lowest of the 3 models. Looking at how the billionaire’s accumulated their wealth or what their citizenship is shows a less accurate picture of our data set, however the AIC values are very similar, so none of the models are significantly better or worse than another.</p>
</section>
<section id="two-variable-linear-regression-models" class="level2">
<h2 class="anchored" data-anchor-id="two-variable-linear-regression-models">Two variable linear regression models</h2>
<div class="cell">

</div>
<p>AIC = 10460.54</p>
<div class="cell">

</div>
<p>AIC = 10462.5</p>
<p>AIC = 10462.5</p>
<div class="cell">

</div>
<p>AIC = 10458.79</p>
<div class="cell">

</div>
<p>AIC = 10472.22</p>
<div class="cell">

</div>
<p>AIC = 10476.53</p>
<div class="cell">

</div>
<p>AIC = 10478.38</p>
<p>For our two variable linear regression models, the additive model “wealth.type + wealth.how.category” is the best fit for our data set. Its AIC is the lowest of the other additive model, as well as the two interaction models.</p>
</section>
<section id="three-variable-linear-regression-models" class="level2">
<h2 class="anchored" data-anchor-id="three-variable-linear-regression-models">Three variable linear regression models</h2>
<div class="cell">

</div>
<p>AIC = 10460.77</p>
<div class="cell">

</div>
<p>AIC = 10479.69</p>
<p>In the one variable linear regression models, the wealth type model had the lowest AIC, indicating that in a one variable linear regression, wealth type is the best fit for modeling billionaire wealth.</p>
<p>In the two variable linear regression models, the additive wealth type and citizenship model had the lowest AIC, indicating that in a two variable linear regression, an additive wealth type and citizenship model is the best fit for modeling billionaire wealth.</p>
<p>Similarly, in the three variable linear regression models, the additive model had the lowest AIC, indicating that in a three variable linear regression, an additive model is the best fit for modeling billionaire wealth.</p>
<p>Overall, our two and three variable linear regression models indicate that in modeling billionaire wealth, the additive model is a better fit than the interaction model. In all the two and three variable models, the additive models had lower AIC values than their corresponding interaction models, indicating better fit.</p>
</section>
</section>
<section id="conclusion" class="level1">
<h1>Conclusion</h1>
<p>Throughout this project, we set out to determine how wealth category, citizenship, and wealth type relate to billionaire net worths in the year of 2014. We hypothesized that <strong>financial</strong> wealth, <strong>European</strong> citizenship, and inheritance are linked to billionaires possessing higher net worths.</p>
<p>To test our hypothesis, we began by grouping our data set by billionaires possessing citizenship in a European country and those with Non-European citizenship. We then calculated the summary statistics (mean, median, standard deviation) of the variable wealth.worth and then again but by filtering wealth.worth through different variables.</p>
<p>The mean of the billionaires net worth is 3.9 billion dollars. The median 2.1 billion dollars and the standard deviation 5.75 billion dollars. By grouping it by wealth.how.industry, we observed the drastic differences in total net worth, depending on the industry they accumulated wealth through. Technology (Computer) producing the richest billionaires with a mean of 5.23 billion dollars. With wealth.how.category, we notice that wealth was accumulated the most on average in Non-Traded Sectors. With the variable citizenship_euro, we came to the conclusion that on average the wealthier billionaires come from a European country, with their net worth coming in at 4.04 billion dollars, compared to the Non-Europeans at 3.85 billion dollars. Wealth.type indicates to us that those who inherited their wealth have on average a higher net worth. We then created box plots and pie charts to visually graph these results.</p>
<p>Lastly, we created linear regression models, both additive and interaction. The one variable wealth type linear regression model yielded the lowest AIC, indicating that wealth type is the best out of our variables of interest for modeling billionaire wealth. Considering that financial wealth accounted for a large proportion of the billionaires in the data set, our results provide evidence that financial wealth may have a relationship with billionaire status. It is important to note, however, that the AIC’s for all of these models were relatively similar and the difference may not be significant enough to consider one model as definitively better than the others. We find that one average, the wealthiest billionaires have derived wealth from inheritance. Therefore, our study provides evidence that inheritance is associated with a higher net worth. Our study also supports our hypothesis that European citizenship is associated with higher net worths.</p>
</section>
<section id="works-cited" class="level1">
<h1>Works Cited</h1>
<ol type="1">
<li><p>Joe Hasell, Max Roser, Esteban Ortiz-Ospina and Pablo Arriagada (2022) - “Poverty”. Published online at OurWorldInData.org. Retrieved from: https://ourworldindata.org/poverty</p></li>
<li><p>Myers, J. (2021, December 10). These charts show the growing gap between the world’s richest and poorest. World Economic Forum. Retrieved March 29, 2023, from https://www.weforum.org/agenda/2021/12/global-income-inequality-gap-report-rich-poor/</p></li>
<li><p>Freund, C., &amp; Oliver, S. (2016). (working paper). The Origins of the Superrich: The Billionaire Characteristics Database. Peterson Institute for Economics.</p></li>
<li><p>Goldberg, Robyn. “Billionaire Census.” Altrata, 1 Aug.&nbsp;2022, https://altrata.com/reports/billionaire-census-2022.</p></li>
<li><p>Elinder, Mikael, et al.&nbsp;“Inheritance and Wealth Inequality: Evidence from Population Registers.” SSRN Electronic Journal, 2016, https://doi.org/10.2139/ssrn.2757949.</p></li>
<li><p>Avery, Koop “Mapped: The World’s Billionaire Population, by Country.” Visual Capitalist, 24 Sept.&nbsp;2022, https://www.visualcapitalist.com/mapped-the-worlds-billionaire-population-by-country/</p></li>
</ol>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>